/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as WorkRouteImport } from './routes/work'
import { Route as PackagesIndexRouteImport } from './routes/packages/index'
import { Route as PackagesWebsiteRouteImport } from './routes/packages/website'
import { Route as PackagesWebsiteAutomationRouteImport } from './routes/packages/website-automation'
import { Route as PackagesWebsiteAutomationAiRouteImport } from './routes/packages/website-automation-ai'
import { Route as PackagesWebsiteAutomationSeoRouteImport } from './routes/packages/website-automation-seo'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesAiRouteImport } from './routes/services/ai'
import { Route as ServicesAutomationRouteImport } from './routes/services/automation'
import { Route as ServicesCrmRouteImport } from './routes/services/crm'
import { Route as ServicesGoogleBusinessProfileRouteImport } from './routes/services/google-business-profile'
import { Route as ServicesPaymentsRouteImport } from './routes/services/payments'
import { Route as ServicesSeoRouteImport } from './routes/services/seo'
import { Route as ServicesSmsRouteImport } from './routes/services/sms'
import { Route as ServicesWebDesignRouteImport } from './routes/services/web-design'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesWebsiteRoute = PackagesWebsiteRouteImport.update({
  id: '/packages/website',
  path: '/packages/website',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesWebsiteAutomationRoute =
  PackagesWebsiteAutomationRouteImport.update({
    id: '/packages/website-automation',
    path: '/packages/website-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const PackagesWebsiteAutomationAiRoute =
  PackagesWebsiteAutomationAiRouteImport.update({
    id: '/packages/website-automation-ai',
    path: '/packages/website-automation-ai',
    getParentRoute: () => rootRouteImport,
  } as any)
const PackagesWebsiteAutomationSeoRoute =
  PackagesWebsiteAutomationSeoRouteImport.update({
    id: '/packages/website-automation-seo',
    path: '/packages/website-automation-seo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiRoute = ServicesAiRouteImport.update({
  id: '/services/ai',
  path: '/services/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAutomationRoute = ServicesAutomationRouteImport.update({
  id: '/services/automation',
  path: '/services/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCrmRoute = ServicesCrmRouteImport.update({
  id: '/services/crm',
  path: '/services/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGoogleBusinessProfileRoute =
  ServicesGoogleBusinessProfileRouteImport.update({
    id: '/services/google-business-profile',
    path: '/services/google-business-profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPaymentsRoute = ServicesPaymentsRouteImport.update({
  id: '/services/payments',
  path: '/services/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/services/seo',
  path: '/services/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSmsRoute = ServicesSmsRouteImport.update({
  id: '/services/sms',
  path: '/services/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebDesignRoute = ServicesWebDesignRouteImport.update({
  id: '/services/web-design',
  path: '/services/web-design',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/solutions': typeof SolutionsRoute
  '/work': typeof WorkRoute
  '/packages/website': typeof PackagesWebsiteRoute
  '/packages/website-automation': typeof PackagesWebsiteAutomationRoute
  '/packages/website-automation-ai': typeof PackagesWebsiteAutomationAiRoute
  '/packages/website-automation-seo': typeof PackagesWebsiteAutomationSeoRoute
  '/services/ai': typeof ServicesAiRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/crm': typeof ServicesCrmRoute
  '/services/google-business-profile': typeof ServicesGoogleBusinessProfileRoute
  '/services/payments': typeof ServicesPaymentsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/sms': typeof ServicesSmsRoute
  '/services/web-design': typeof ServicesWebDesignRoute
  '/packages/': typeof PackagesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/solutions': typeof SolutionsRoute
  '/work': typeof WorkRoute
  '/packages/website': typeof PackagesWebsiteRoute
  '/packages/website-automation': typeof PackagesWebsiteAutomationRoute
  '/packages/website-automation-ai': typeof PackagesWebsiteAutomationAiRoute
  '/packages/website-automation-seo': typeof PackagesWebsiteAutomationSeoRoute
  '/services/ai': typeof ServicesAiRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/crm': typeof ServicesCrmRoute
  '/services/google-business-profile': typeof ServicesGoogleBusinessProfileRoute
  '/services/payments': typeof ServicesPaymentsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/sms': typeof ServicesSmsRoute
  '/services/web-design': typeof ServicesWebDesignRoute
  '/packages': typeof PackagesIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/solutions': typeof SolutionsRoute
  '/work': typeof WorkRoute
  '/packages/website': typeof PackagesWebsiteRoute
  '/packages/website-automation': typeof PackagesWebsiteAutomationRoute
  '/packages/website-automation-ai': typeof PackagesWebsiteAutomationAiRoute
  '/packages/website-automation-seo': typeof PackagesWebsiteAutomationSeoRoute
  '/services/ai': typeof ServicesAiRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/crm': typeof ServicesCrmRoute
  '/services/google-business-profile': typeof ServicesGoogleBusinessProfileRoute
  '/services/payments': typeof ServicesPaymentsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/sms': typeof ServicesSmsRoute
  '/services/web-design': typeof ServicesWebDesignRoute
  '/packages/': typeof PackagesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/solutions'
    | '/work'
    | '/packages/website'
    | '/packages/website-automation'
    | '/packages/website-automation-ai'
    | '/packages/website-automation-seo'
    | '/services/ai'
    | '/services/automation'
    | '/services/crm'
    | '/services/google-business-profile'
    | '/services/payments'
    | '/services/seo'
    | '/services/sms'
    | '/services/web-design'
    | '/packages/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/solutions'
    | '/work'
    | '/packages/website'
    | '/packages/website-automation'
    | '/packages/website-automation-ai'
    | '/packages/website-automation-seo'
    | '/services/ai'
    | '/services/automation'
    | '/services/crm'
    | '/services/google-business-profile'
    | '/services/payments'
    | '/services/seo'
    | '/services/sms'
    | '/services/web-design'
    | '/packages'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/solutions'
    | '/work'
    | '/packages/website'
    | '/packages/website-automation'
    | '/packages/website-automation-ai'
    | '/packages/website-automation-seo'
    | '/services/ai'
    | '/services/automation'
    | '/services/crm'
    | '/services/google-business-profile'
    | '/services/payments'
    | '/services/seo'
    | '/services/sms'
    | '/services/web-design'
    | '/packages/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  SolutionsRoute: typeof SolutionsRoute
  WorkRoute: typeof WorkRoute
  PackagesWebsiteRoute: typeof PackagesWebsiteRoute
  PackagesWebsiteAutomationRoute: typeof PackagesWebsiteAutomationRoute
  PackagesWebsiteAutomationAiRoute: typeof PackagesWebsiteAutomationAiRoute
  PackagesWebsiteAutomationSeoRoute: typeof PackagesWebsiteAutomationSeoRoute
  ServicesAiRoute: typeof ServicesAiRoute
  ServicesAutomationRoute: typeof ServicesAutomationRoute
  ServicesCrmRoute: typeof ServicesCrmRoute
  ServicesGoogleBusinessProfileRoute: typeof ServicesGoogleBusinessProfileRoute
  ServicesPaymentsRoute: typeof ServicesPaymentsRoute
  ServicesSeoRoute: typeof ServicesSeoRoute
  ServicesSmsRoute: typeof ServicesSmsRoute
  ServicesWebDesignRoute: typeof ServicesWebDesignRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/': {
      id: '/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/website': {
      id: '/packages/website'
      path: '/packages/website'
      fullPath: '/packages/website'
      preLoaderRoute: typeof PackagesWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/website-automation': {
      id: '/packages/website-automation'
      path: '/packages/website-automation'
      fullPath: '/packages/website-automation'
      preLoaderRoute: typeof PackagesWebsiteAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/website-automation-ai': {
      id: '/packages/website-automation-ai'
      path: '/packages/website-automation-ai'
      fullPath: '/packages/website-automation-ai'
      preLoaderRoute: typeof PackagesWebsiteAutomationAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/website-automation-seo': {
      id: '/packages/website-automation-seo'
      path: '/packages/website-automation-seo'
      fullPath: '/packages/website-automation-seo'
      preLoaderRoute: typeof PackagesWebsiteAutomationSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai': {
      id: '/services/ai'
      path: '/services/ai'
      fullPath: '/services/ai'
      preLoaderRoute: typeof ServicesAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/automation': {
      id: '/services/automation'
      path: '/services/automation'
      fullPath: '/services/automation'
      preLoaderRoute: typeof ServicesAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/crm': {
      id: '/services/crm'
      path: '/services/crm'
      fullPath: '/services/crm'
      preLoaderRoute: typeof ServicesCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/google-business-profile': {
      id: '/services/google-business-profile'
      path: '/services/google-business-profile'
      fullPath: '/services/google-business-profile'
      preLoaderRoute: typeof ServicesGoogleBusinessProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/payments': {
      id: '/services/payments'
      path: '/services/payments'
      fullPath: '/services/payments'
      preLoaderRoute: typeof ServicesPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/services/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/sms': {
      id: '/services/sms'
      path: '/services/sms'
      fullPath: '/services/sms'
      preLoaderRoute: typeof ServicesSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-design': {
      id: '/services/web-design'
      path: '/services/web-design'
      fullPath: '/services/web-design'
      preLoaderRoute: typeof ServicesWebDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  SolutionsRoute: SolutionsRoute,
  WorkRoute: WorkRoute,
  PackagesWebsiteRoute: PackagesWebsiteRoute,
  PackagesWebsiteAutomationRoute: PackagesWebsiteAutomationRoute,
  PackagesWebsiteAutomationAiRoute: PackagesWebsiteAutomationAiRoute,
  PackagesWebsiteAutomationSeoRoute: PackagesWebsiteAutomationSeoRoute,
  ServicesAiRoute: ServicesAiRoute,
  ServicesAutomationRoute: ServicesAutomationRoute,
  ServicesCrmRoute: ServicesCrmRoute,
  ServicesGoogleBusinessProfileRoute: ServicesGoogleBusinessProfileRoute,
  ServicesPaymentsRoute: ServicesPaymentsRoute,
  ServicesSeoRoute: ServicesSeoRoute,
  ServicesSmsRoute: ServicesSmsRoute,
  ServicesWebDesignRoute: ServicesWebDesignRoute,
  PackagesIndexRoute: PackagesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
